### ISSUE TITLE
Question: Are subdirectories intended to be supported?

### ISSUE THREAD

**Issue by joncalhoun** [devlocker/tychus#6]
TL;DR I'm starting my app like this:

```
tychus go run cmd/server/*.go
```

Then I'm editing html files use in the web app's templates. Things like `views/users/new.gohtml`.

When I make these changes they don't seem to cause a reboot of the app w/ Tychus. Not sure if this is supposed to be supported or not.

**Comment by PatKoperwas** [comment]
They're supposed to be. Can you run this:

```
tychus "go run cmd/server/*.go" --debug
```

The `--debug` flag is going to output a whole bunch of stuff. Can you copy / paste the output of what you get here?

As a sidenote, the reboot doesn't happen until you make a request to the Proxy - which starts on port 4000 by default.

**Comment by joncalhoun** [comment]
Well.. everything appears to be working now. 😬

Since I can't replicate any longer I'm going to close the issue. If it somehow ever happens again I'll run w/ the debug flag and get you output. Sorry to bother you!

**Comment by PatKoperwas** [comment]
All good. Glad to hear it works!
